#表名称前缀，实体类生成会将表名前缀去掉
mysql:    
  address: 43.143.136.7        #数据库连接信息
  port: 3306
  username: root                #用户名
  password: 1qaz!QAZ              #密码
  database: ginapi             #数据库
dir:
  tmpl: templates/v1/exam          #模版路径
  out: templates/v2/exam         #代码生成路径