project:            #涉及代码中依赖包的路径{project.name}/{project.package}/{project.module}
  name: halo        #项目名称
  packName: app      #包名
  module: blog      #模块名称
table:
  names: t_user     #生成表的名称多个用逗号隔开如t_user,t_role
  prefix: t_        #表名称前缀，实体类生成会将表名前缀去掉
mysql:              #数据库连接信息
  username: root              #用户名
  password: 1qaz!QAZ          #密码
  driver: mysql               #驱动
  url: tcp(43.143.136.7:3306) #url
  schema: go_test             #数据库
dir:
  tmpl: templates/go/app          #模版路径
  out: templates/out           #代码生成路径